Event Sourcing
tsb99x/checkpoint pull request #10
Opened 2020-10-21 18:23 UTC by tsb99x

Move to event sourcing approach to improve the tasks storage. Think about moving to the IndexedDB in the future.

2020-10-22 13:03 UTC, GKsenon requested changes

2020-10-22 13:03 UTC, GKsenon commented on src/App.vue
> +            ...actions,
It's not obvious which actions and getters are used by the component.

2020-10-22 13:03 UTC, GKsenon commented on src/state.js
> +let events = loadJson(EVENTS, [])
An explicit initialization through a function call would be easier to understand.

2020-10-22 18:14 UTC, tsb99x commented on src/App.vue
> +            ...actions,
Yes, refactored to call actions explicitly through the component's methods.

2020-10-22 18:16 UTC, tsb99x commented on src/state.js
> +let events = loadJson(EVENTS, [])
Yup, wrapped the initialization into an appropriate function. A call to this function is done at the `main.js`.

2020-10-24 10:02 UTC, GKsenon approved these changes

2020-10-24 16:16 UTC, merged