Tasks editing
tsb99x/checkpoint pull request #12
Opened 2020-10-25 18:08 UTC by tsb99x

2020-10-26 12:12 UTC, GKsenon requested changes

2020-10-26 12:12 UTC, GKsenon commented on tests/e2e/specs/test.js
> +    it('should edit the task title properly', () => {
The test is too long (LOC). Each test case should be in its own `it` block.

2020-10-26 18:04 UTC, tsb99x commented on tests/e2e/specs/test.js
> +    it('should edit the task title properly', () => {
I agree. Splitted it into several blocks. I would probably need to do the same for other tests.

2020-10-27 09:45 UTC, GKsenon approved these changes

2020-10-27 15:26 UTC, merged